(()=>{'use strict';
const U='https://djfjqecahztogacliav.supabase.co',K='sb_publishable_tm8Tid_HSYtu6cxXQ3ddKA_RWN15BSB';
const sb=window.__animeTrackerSupabase||(window.supabase?.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}));
if(sb&&!window.__animeTrackerSupabase)window.__animeTrackerSupabase=sb;
if(!sb)return;
const $=id=>document.getElementById(id);
function cleanAuthUrl(){try{const u=new URL(location.href);const hadHash=!!u.hash;const hadQ=['code','type','access_token','refresh_token','expires_at','expires_in','token_type','sb','confirmed'].some(k=>u.searchParams.has(k));if(hadHash||hadQ){u.hash='';['code','type','access_token','refresh_token','expires_at','expires_in','token_type','sb','confirmed'].forEach(k=>u.searchParams.delete(k));history.replaceState({},document.title,u.href)}}catch{}}
function style(){if($('atResetStyle'))return;const s=document.createElement('style');s.id='atResetStyle';s.textContent='.at-reset{position:fixed;inset:0;z-index:100001;display:grid;place-items:center;padding:24px;background:rgba(0,0,0,.84);backdrop-filter:blur(16px)}.at-reset-card{width:min(440px,100%);padding:28px;border:1px solid #303030;border-radius:20px;background:#111;box-shadow:0 30px 100px rgba(0,0,0,.55)}.at-reset-card h2{margin:8px 0}.at-reset-card p{margin:0 0 14px;color:#999;font-size:11px;line-height:1.5}.at-reset-card input{width:100%;padding:12px;border:1px solid #333;border-radius:10px;background:#181818;color:#eee;margin-top:8px}.at-reset-actions{display:flex;gap:8px;margin-top:14px}.at-reset button{border:1px solid #333;border-radius:10px;padding:11px 14px;background:#eee;color:#111;font-weight:800}.at-reset button.secondary{background:#181818;color:#ddd}.at-reset-msg{margin-top:10px;color:#aaa;font-size:10px;min-height:16px}';document.head.appendChild(s)}
function resetModal(){style();document.querySelector('.at-reset')?.remove();const d=document.createElement('div');d.className='at-reset';d.innerHTML='<div class="at-reset-card"><h2>Nueva contraseña</h2><p>El enlace es válido. Elige tu nueva contraseña para terminar.</p><input id="atReset1" type="password" placeholder="Nueva contraseña"><input id="atReset2" type="password" placeholder="Repite la contraseña"><div class="at-reset-actions"><button id="atResetSave">Guardar contraseña</button><button id="atResetClose" class="secondary">Cerrar</button></div><div id="atResetMsg" class="at-reset-msg"></div></div>';document.body.appendChild(d);$('atResetClose').onclick=()=>{d.remove();cleanAuthUrl()};$('atResetSave').onclick=async()=>{const a=$('atReset1').value,b=$('atReset2').value,m=$('atResetMsg'),btn=$('atResetSave');if(a.length<6){m.textContent='La contraseña debe tener al menos 6 caracteres.';return}if(a!==b){m.textContent='Las contraseñas no coinciden.';return}btn.disabled=true;btn.textContent='Guardando…';const {error}=await sb.auth.updateUser({password:a});if(error){m.textContent=error.message;btn.disabled=false;btn.textContent='Guardar contraseña';return}m.textContent='Contraseña actualizada.';setTimeout(()=>{d.remove();cleanAuthUrl()},700)}}
sb.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY')resetModal();if(event==='SIGNED_IN'&&session?.user)cleanAuthUrl()});
window.addEventListener('load',()=>{const h=location.hash||'';const t=new URLSearchParams(h.replace(/^#/,'')).get('type');if(t==='recovery')resetModal();else if(t==='signup'||t==='email')cleanAuthUrl()})
})();